# Generated by Django 5.1.4 on 2024-12-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agency', '0002_imagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
